-- Migrare PARTE 8/13
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSCU4929119', '42G1', 19, 6396, 'CONTROLERE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'AXIU1628298', '45G1', 553, 7723.05, 'IMBRACAMINTE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU3691887', '22G1', 530, 3005.95, 'SET TOALETA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TRHU2425370', '22G1', 252, 20260, 'FOLIE PVC', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'GLDU3733893', '22G1', 10, 21985.88, 'TABLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCLU2128703', '22G1', 9, 21965.2, 'TABLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CXDU1989171', '22G1', 17, 16425.4, 'COMPONENTE RULMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'GLDU9635960', '22G1', 17, 16366.9, 'COMPONENTE RULMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6011601', '22G1', 17, 16314.9, 'COMPONENTE RULMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6718744', '22G1', 17, 16314.9, 'COMPONENTE RULMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU6058080', '45G1', 88, 9208.8, 'PANOU PERETE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCNU2364352', '45G1', 2, 4690, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU5832346', '22G1', 60, 19498, 'FIBRA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCLU7767564', '45G1', 23, 3514, 'PLASTIC ARMAT CU FIBRA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FTAU1384071', '22G1', 36, 20000.7, 'PIESE AUTO', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU2144542', '22G1', 30, 22535.12, 'SAIBE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6033196', '22G1', 20, 10672, 'TEVI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU3054045', '22G1', 353, 4262, 'CUTII CONSERVE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'BMOU2208891', '22G1', 14, 18410, 'SARMA CORD', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FCIU4364398', '22G1', 12, 17414, 'SARMA CORD', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU5673590', '22G1', 12, 17434, 'SARMA CORD', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU3065203', '22G1', 14, 18407, 'SARMA CORD', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU3043942', '22G1', 12, 17416, 'SARMA CORD', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'SEGU2875783', '22G1', 12, 17422, 'SARMA CORD', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU4535214', '45G1', 30, 21000, 'TRANSFORMATOARE, COMUTATOARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCNU2773561', '45G1', 34, 12780, 'TRANSFORMATOARE, COMUTATOARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCNU1151075', '45G1', 76, 24396, 'FIRE POLIESTER', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU2000363', '22G1', 880, 22176, 'OXID DE FIER', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'IPXU3793675', '22G1', 18, 4800, 'INVERTER, CABLU, CONECTORI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGBU9855635', '45G1', 987, 5702.5, 'COMPRESE CU TIFON, SET PERFUZIE, ETC', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU1771200', '22G1', 80, 22400, 'PIEI IN SARAMURA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'AXIU2944602', '22G1', 21, 25416, 'PARDOSELI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FBIU0188241', '22G1', 20, 25240, 'PARDOSELI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU3451422', '22G1', 21, 25504, 'PARDOSELI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU3799676', '22G1', 20, 25466, 'PARDOSELI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6201047', '22G1', 21, 25416, 'PARDOSELI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU1211749', '22G1', 20, 25335, 'PARDOSELI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'IKSU8621402', '45G1', 16, 15170.2, 'FIRE POLIETILENA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCNU7895182', '45G1', 63, 23183, 'FIRE POLIESTER', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU4978790', '45G1', 483, 18103.11, 'MOBILIER', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU5206855', '45G1', 768, 9599.5, 'DISPOZITIV URCAT SCARI , PAT URGENTA , SCAUN ROTILE, PARAVAN', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU2274320', '22G1', 14, 22268, 'SARMA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU1872815', '22G1', 14, 22259, 'SARMA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU1875619', '22G1', 14, 22289, 'SARMA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCLU5902520', '45G1', 2, 4905, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU8460682', '45G1', 3, 4635, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU8674839', '45G1', 3, 4635, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAAU5924921', '45G1', 2, 5140, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU6777404', '45G1', 3, 6865, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU5831364', '45G1', 2, 5070, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSCU5352382', '45G1', 2, 5815, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU8114144', '45G1', 3, 6414, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSCU5413718', '45G1', 3, 6190, 'AUTOVEHICULE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FSCU7780818', '22G1', 5, 21795, 'TABLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGHU0931675', '22G1', 5, 21760, 'TABLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU2959949', '22G1', 5, 21925, 'TABLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'XINU1663360', '22G1', 5, 21700, 'TABLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSCU5386607', '45G1', 3, 4604, 'AUTOVEHICULE', '25MT01000P4EC33AT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FCIU2236799', '22G1', 960, 24592, 'DIOXID TITANIU', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU9858646', '45G1', 134, 7260, 'ECHIPAMENTE LOC DE JOACA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU3269210', '22G1', 31, 20850, 'CUIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSCU1899448', '22G1', 960, 24592, 'DIOXID DE TITANIU', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU3120050', '22G1', 960, 24592, 'DIOXID DE TITANIU', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU7164539', '45G1', 251, 13887.83, 'MASINI DE SPALAT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU7188680', '45G1', 251, 13887.83, 'MASINI DE SPALAT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9199969', '45G1', 53, 5787, 'FRIGIDERE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9166570', '45G1', 216, 13765.68, 'MASINI DE SPALAT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9166610', '45G1', 153, 7512.3, 'USCATOARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9166522', '45G1', 171, 7609.5, 'USCATOARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9166651', '45G1', 171, 7609.5, 'USCATOARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9166590', '45G1', 225, 14715, 'MASINI DE SPALAT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU9168438', '45G1', 225, 14109.75, 'MASINI DE SPALAT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FFAU3508528', '45G1', 24, 17598.75, 'ROTI DINTATE, ANGRENAJE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'DFSU6545228', '45G1', 21, 21386, 'PIESE DE TRANSMISIE PENTRU TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU7871526', '45G1', 13, 21289, 'PIESE DE TRANSMISIE PENTRU TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU5411637', '45G1', 21, 21386, 'PIESE DE TRANSMISIE PENTRU TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU5536526', '45G1', 13, 19466, 'PIESE DE TRANSMISIE PENTRU TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU4385479', '45G1', 13, 21134, 'PIESE DE TRANSMISIE PENTRU TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU4456926', '45G1', 13, 19466, 'PIESE DE TRANSMISIE PENTRU TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU7583415', '45G1', 15, 20992, 'PARTI TRANSMISII TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU8125232', '45G1', 9, 21575, 'PARTI TRANSMISII TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU5222000', '45G1', 9, 21575, 'PARTI TRANSMISII TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGHU6059554', '45G1', 9, 21575, 'PARTI TRANSMISII TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU4684290', '45G1', 13, 19466, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FDCU0273495', '45G1', 21, 21386, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU7796530', '45G1', 13, 19466, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU4739166', '45G1', 21, 21386, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU7704470', '45G1', 13, 21289, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGBU5963734', '45G1', 13, 21134, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU4761709', '45G1', 9, 21575, 'SISTEM TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU7648996', '45G1', 9, 22376, 'SISTEM TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU4256333', '45G1', 9, 21575, 'SISTEM TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU4570220', '45G1', 9, 21575, 'SISTEM TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU6750725', '45G1', 15, 20992, 'SISTEM TRACKER SOLAR', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSCU5367248', '45G1', 24, 17598.75, 'ROTI DINTATE, ANGRENAJE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'DFSU6450966', '45G1', 9, 16682, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FCGU1985080', '45G1', 13, 20046, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU6526459', '45G1', 13, 21134, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU5821880', '45G1', 11, 17950, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'SEGU6091558', '45G1', 13, 21134, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCLU5637094', '45G1', 17, 23473, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU7837496', '45G1', 13, 19466, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU8977174', '45G1', 9, 22376, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU6414447', '45G1', 21, 21386, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCLU7791215', '45G1', 9, 21575, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TEMU6895819', '45G1', 21, 22261, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TIIU4159799', '45G1', 13, 23212, 'PARTI TRACKERE SOLARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCNU2909051', '45G1', 890, 9078, 'MASTI MEDICALE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CRSU9081334', '45G1', 940, 25818, 'PLASA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU8949797', '45G1', 596, 9536, 'SERINGI STERILE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TEMU2017501', '22G1', 40, 21432, 'ECHIPAMENT FITNESS', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAAU7522670', '45G1', 588, 23996, 'FIBRA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU5731899', '45G1', 510, 23836, 'SALTELE, TESATURI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU4453060', '45G1', 35, 25724.78, 'BENZI SIGILARE , CUTII CARTON', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6895349', '22G1', 20, 14372, 'CHIMICALE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'GLDU5491227', '22G1', 22, 20555, 'PLASA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU3167083', '22G1', 22, 20650, 'PLASA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU2784206', '22G1', 22, 20469, 'PLASA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU2716714', '22G1', 22, 20445, 'PLASA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU2780267', '22G1', 22, 20575, 'PLASA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU3592583', '22G1', 22, 20509, 'PLASA DE STICLA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3110683', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3111247', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3111756', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3111782', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3113255', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3113300', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3117179', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3117224', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3118200', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3119593', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3119891', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3121271', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3121332', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3123356', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU3125317', '22G1', 20, 20060, 'PIGMENTI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU2594460', '22G1', 80, 21600, 'PIEI IN SARAMURA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FFAU3074587', '45G1', 1532, 10570.8, 'LENJERII', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1117782', '22G1', 5, 4640, 'BOBINA OTEL', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575021', '45G1', 76, 4620.8, 'FRIGIDERE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575187', '45G1', 76, 4620.8, 'FRIGIDERE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1112883', '22G1', 1, 24039.6, 'POLIMERI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1119450', '22G1', 1, 24039.6, 'POLIMERI', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5585987', '45G1', 58, 25245, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FCIU3860881', '22G1', 44, 21534, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU1872431', '22G1', 30, 22118, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1105821', '22G1', 34, 22883, 'HARTIE GLOSS', '25ES01000O8LCPGAT0', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1105842', '22G1', 32, 21678, 'HARTIE GLOSS', '25ES01000O8LCMQAT8', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1105950', '22G1', 32, 21680, 'HARTIE GLOSS', '25ES01000O8LCMQAT8', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1106108', '22G1', 33, 22026, 'HARTIE GLOSS', '25ES01000O8LCMQAT8', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575274', '45G1', 20, 24999, 'HARTIE TERMICA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575280', '45G1', 19, 24127, 'HARTIE TERMICA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575422', '45G1', 19, 24055, 'HARTIE TERMICA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575628', '45G1', 20, 24874, 'HARTIE TERMICA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575633', '45G1', 20, 25028, 'HARTIE TERMICA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5575654', '45G1', 19, 24064, 'HARTIE TERMICA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU5335720', '22G1', 35, 24811, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU1489339', '22G1', 1040, 14612.5, 'SINE SERTAR', '25MT01000O9COEKAT0', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCLU2970202', '22G1', 1567, 24385, 'MECANISME INCUIETORI', '25MT01000O9COODAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU7250786', '45G1', 266, 5475.4, 'JUCARII', '25MT01000O9CHGHAT2', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAAU5093330', '45G1', 52, 25076, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU9348220', '45G1', 54, 25410, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TIIU5997693', '45G1', 52, 25444, 'HARTIE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU6771280', '45G1', 110, 14027.689, 'CIRCUITE IMPRIMANTE, MASINI DE FILTRARE,', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TIIU4392373', '45G1', 633, 16609.84, 'PRODUSE CERAMICE REFACTARE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU5714430', '22G1', 63, 1329.54, 'EFECTE PERSONALE', '25MT01000P3RRG1AT4', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU1889537', '22G1', 16, 22304, 'CAUCIUC', '25MT01000O9CJ00AT4', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU3039860', '22G1', 16, 22304, 'CAUCIUC', '25MT01000O9CJ00AT4', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGBU2497268', '22G1', 16, 22304, 'CAUCIUC', '25MT01000O9CJ00AT4', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU2086346', '22G1', 16, 19294, 'PLACI CAUCIUC', '25MT01000O9CDNIAT0', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU6859124', '22G1', 196, 7691.04, 'FIRE', '25MT01000O9CLHLAT0', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'BMOU2600217', '22G1', 16, 22304, 'CAUCIUC', '25MT01000O9CIY3AT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6272483', '22G1', 16, 22304, 'CAUCIUC', '25MT01000O9CIY3AT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TEMU2024497', '22G1', 16, 22304, 'CAUCIUC', '25MT01000O9CIY3AT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU6843168', '45G1', 32, 22539.6, 'HARTIE', '25MT01000O9CJLRAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU8817828', '45G1', 791, 4217.69, 'COSURI GUNOI', '25RO01000P5H4S2AT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU6242960', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU1894397', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU1018600', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU1772469', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU1772812', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU3727800', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TEMU5745440', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGHU0602432', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5GX8VAT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU2827751', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'DFSU2895233', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'GAOU2448037', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'GLDU5361049', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU5373798', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU1948464', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU2600865', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU2052507', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'SEGU2935985', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGBU3160271', '22G1', 20, 24240, 'FULGI PET', '25RO01000P5H4RCAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU1441314', '22G1', 16, 22304, 'CAUCIUC', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU3669980', '22G1', 16, 22304, 'CAUCIUC', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU3701130', '22G1', 16, 22304, 'CAUCIUC', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU1520959', '22G1', 16, 22304, 'CAUCIUC', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGBU3620680', '22G1', 80, 20905, 'SIROP FRUCTE', '25MT01000OJXU65AT6', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU8356937', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VQAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU5543253', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VQAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU8833430', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VQAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAAU8652128', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FFAU5528098', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'GAOU7548785', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU5439088', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU5722623', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU5681773', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU7110916', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU7548034', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU8473623', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU5723893', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'SEKU4007970', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TLLU7957032', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCK4VNAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FFAU5541335', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZ3UAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU5777550', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZ3UAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU4375613', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZ3UAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU7951207', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZ3UAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TGHU5183236', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZ3UAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU6875526', '45G1', 1584, 22936.32, 'BERE', '25ES01000OREK3AAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU7777550', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU4426574', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU4071900', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU4509133', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU4528175', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU6849981', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU4325555', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU4614985', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU4660189', '42G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU6429522', '45G1', 1584, 22936.32, 'BERE', '25ES01000OCJZJKAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TCNU1313638', '45G1', 1584, 22936.32, 'BERE', '25ES01000ORENIPAT5', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'UETU8085840', '45G1', 960, 24336, 'PIPER', '25MT01000OJXONWAT9', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU6557983', '45G1', 110, 9411, 'MASINI DE SPALAT', '25ES01000O54TNRAT8', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU7994393', '45G1', 215, 14709, 'ANVELOPE', '25ES01000O550PXAT3', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'CAIU7460360', '45G1', 14, 27990, 'PLACAJE', '25ES01000O54TUUAT2', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TIIU5896996', '45G1', 14, 27980, 'PLACAJE', '25ES01000O54TUUAT2', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU7064606', '45G1', 14460, 5068.98, 'PERIUTE DE DINTI', '25ES01000O550HIAT0', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'BMOU2816335', '22G1', 42, 25208, 'SURUBURI', '25ES01000O54TMOAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FCIU5130291', '22G1', 42, 24053, 'SURUBURI', '25ES01000O54TMOAT7', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU6477980', '45G1', 22, 17335, 'TEVI', '25ES01000O4YBFCAT0', 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSNU7091213', '45G1', 2669, 9568, 'FARFURII', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'FCIU5523540', '22G1', 14, 23800, 'ARTICOLE PIATRA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSBU1301383', '22G1', 17, 23930, 'ARTICOLE PIATRA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU5964070', '22G1', 17, 21700, 'ARTICOLE PIATRA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MEDU6483336', '22G1', 18, 24400, 'ARTICOLE PIATRA', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'TLLU7651124', '45G1', 238, 14085.65, 'ANVELOPE', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSDU1275255', '22G1', 17, 25100, 'GRANIT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU2794863', '22G1', 17, 25500, 'GRANIT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU2795160', '22G1', 18, 24000, 'GRANIT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;
INSERT IGNORE INTO manifests (manifest_number, arrival_date) VALUES ('154', '2025-11-27');
INSERT INTO manifest_entries (manifest_id, container_number, container_type, packages, weight, goods_description, summary_number, operation_type) SELECT id, 'MSMU2795474', '22G1', 15, 25200, 'GRANIT', NULL, 'I' FROM manifests WHERE manifest_number = '154' LIMIT 1;

-- DONE PART 8/13
